name: Add File to Repository
on:
  push:
    branches:
      - main
jobs:
  addFile:
    name: Add File
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Create File
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./cloc.txt"
          FILE_DATA: "file content"
      - name: Commit and Push Changes
        run: |
          ls -l > textlist.txt
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --quiet; then
            git commit -m "Add new file"
            git push origin main
          else
            echo "No changes to commit"
            exit 0
          fi