name: Create File in Test Directory
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Create File in cloc test
        run: |
          mkdir -p json
          echo "This is the content of the new file 1." > json/newFile.json
          # echo pwd
          # ls -l
     
      - name: Install CLOC
        run: sudo apt-get install -y cloc
      
      - name: Count Lines Of Code and Save to newFile.json
        run: |
          cloc . --json > newFile.json
          echo "" >> test/newFile.json
          echo "CLOC JSON OUTPUT:" >> json/newFile.json
          cat cloc.jsonc >> json/newFile.json

     
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add json/newFile.json
          git commit -m "Add new file to cloc-test directory"
          git push origin main
          