name: Create File in Test Directory
on:
  push:
    branches:
      - main
jobs:
  createFile:
    name: Create File
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - name: Create File
        run: |
          mkdir -p cloc-test
          echo "This is the content of the new file." > cloc-test/newFile.txt
          echo pwd
          ls -l
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add cloc-test/newFile.txt
          if ! git diff --quiet; then
            git commit -m "Add new file to cloc-test directory"
            git push origin main
          else
            echo "No changes to commit"
            exit 0
          fi