name: Create File in Test Directory
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
     
      - name: Create File in cloc test
        run: |
          mkdir -p json
          echo "This is the content of the new file 1." > json/newFile.txt
          echo pwd
          ls -l
      - name: Install CLOC
        run: |
          sudo apt install cloc jq
      - name: Generate cloc json
        run: |
          cloc . --json > test/cloc.json
          jq . test/cloc.json > test/cloc.json
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add test/cloc.json
          git commit -m "Add new file to cloc-test directory"
          git push origin main
          